src/utils/web3Utils.js
src/views/pages/Pools/Pools.js

web3Utils #24

---

src/components/WalletSelect/WalletSelect.js
src/utils/web3.js

added function in web3 to add a token to metamask/etc
binance chain wallet will require the method to be added before it will work, but the injecteds and metamask work
when integrating this function be sure to dynamically populate the address, symbol name, decimals and token icon for best UI/UX
closes #11

function to add token to watchlist

---

src/utils/web3Sparta.js

add contract functions to web3Sparta

---

src/utils/web3Bond.js
src/utils/web3Dao.js
src/utils/web3Router.js
src/utils/web3Sparta.js
src/utils/web3Utils.js
src/views/pages/AddLiquidity.js

add all relevant bond contract functions
closes #31

add bond contract functions

---

src/utils/web3Router.js

add router contract functions

---

src/index.js
src/store/confirmation/actions.js
src/store/confirmation/actions.test.js
src/store/info/actions.js
src/store/info/actions.test.js
src/store/pricing/actions.test.js
src/store/pricing/reducer.js
src/store/sparta/action.test.js
src/store/sparta/actions.js
src/store/sparta/index.js
src/store/sparta/reducer.js
src/store/sparta/selector.js
src/store/sparta/types.js
src/utils/web3Sparta.js

This PR convert Sparta functionalities in a store selector, there is a test that fail but it looks like it is about the address that I passed because the error show like this:
```
{
type: 'SPARTA_ERROR',
error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32000,\"message\":\"missing from address\"}}\n", error={"code":-32000}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"to\":\"0x6e812dd5b642334bbd17636d3865ce82c3d4d7eb\",\"data\":\"0xaad3ec960000000000000000000000004102773565d82c8b0785f1262cfe75f04f17077700000000000000000000000000000000000000000000000000000000000003e8\"}],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://data-seed-prebsc-2-s1.binance.org:8545/", code=SERVER_ERROR, version=web/5.0.13)
at …
```

Web3 sparta redux #47

---

src/index.js
src/store/web3All/actions.js
src/store/web3All/actions.test.js
src/store/web3All/index.js
src/store/web3All/reducer.js
src/store/web3All/selector.js
src/store/web3All/types.js

change web3all to web3

---

src/Providers.js
src/assets/scss/spartan/custom/_dropdown.scss
src/components/WalletSelect/WalletSelect.js
src/components/WalletSelect/walletTypes.js

I made possible to connect with walletconnect (also works with binance chain and metamask). There is an issue with the chainId which throw error when try to connect with testnet. With mainnet works fine. Also I fix the dropdown of the language

Hand rpc wallet select 81

---

src/utils/extCalls.js

well that was a pretty damn easy fix
closes #90

handle net with bscscan link

---

src/components/DataManager/DataManager.js
src/store/poolFactory/actions.js
src/store/poolFactory/reducer.js

handle curated in finalArray
closes #111

handle curated in finalArray

---

src/components/AssetSelect/AssetSelect.js
src/components/DataManager/DataManager.js
src/store/poolFactory/actions.js
src/store/utilsPricing/actions.test.js
src/views/pages/Pools/Liquidity.js

finalArray refresh on wallet toggle

---

src/components/AssetSelect/AssetSelect.js
src/components/DataManager/DataManager.js
src/views/pages/Pools/Liquidity.js

remove one functional

---

src/components/DataManager/DataManager.js
src/components/WalletSelect/WalletSelect.js
src/store/web3/actions.js
src/store/web3/index.js
src/store/web3/reducer.js
src/store/web3/types.js

separate addNetwork for each wallet

separate addNetwork for each wallet

---

src/components/Dashboard/Dashboard.js
src/utils/web3.js
src/utils/web3Utils.js
src/views/pages/Pools/Swap.js

zap fully functional

---

src/store/bond/actions.js
src/store/dao/actions.js
src/store/router/actions.js
src/store/sparta/actions.js
src/store/web3/actions.js
src/views/pages/Pools/Liquidity.js
src/views/pages/Pools/Overview.js
src/views/pages/PoolsTable.js

fix bnb issue & finalise liq

---

src/components/Share/SharePool.js

Previously only was possible copy or share link clicking in the icon but I fixed this to make possible to do the action clicking in the whole card. Also I fix the position of the button

fix share button

---

src/store/poolFactory/actions.js

smarter tokenIcon handling

---

src/components/AssetSelect/AssetSelect.js
src/views/pages/Pools/Swap.js

complete first major phase for assetSelect, ready for styling
closes #133

assetSelect functional

---

src/components/WalletSelect/WalletSelect.js

I couldn't test for LP tokens if the prop with the address is correct. With this supposedly the first step of the wallet is finish

add button to copy token address and to add in Metamask

---

src/assets/css/styles.css
src/components/AssetSelect/AssetSelect.js
src/components/Share/ShareLink.js
src/components/WalletSelect/WalletSelect.js

cleanup walletSelect & assetSelect

---

src/components/AssetSelect/AssetSelect.js
src/components/WalletSelect/WalletSelect.js
src/views/pages/Dao/LockEarn.js
src/views/pages/Pools/Liquidity.js
src/views/pages/Swap/Swap.js

-SPP for pool tokens
-SPS for synth tokens

new naming convention

---

src/assets/scss/spartan/custom/_variables.scss
src/components/Header/Header.js
src/components/Supply/Supply.js
src/store/bondVault/actions.test.js

plugged in contracts & some tokenmoics

plugged in contracts & some tokenmoics

---

src/store/router/actions.js
src/utils/web3Utils.js
src/views/pages/Swap/Swap.js

synths full functional with steps

---

src/store/poolFactory/actions.js
src/utils/web3.js

disable const imgs

---

src/store/poolFactory/actions.js

closes #186

---

src/views/pages/Dao/Proposals.js
src/views/pages/Pools/BondLiquidity.js
src/views/pages/Pools/RemoveLiquidity.js

closes #221

---

src/utils/web3Utils.js
src/views/pages/Swap/Swap.js

closes #212
at some point go thru swap page and refactor everything to use inputs

refactor swap closes #212

---

src/assets/css/styles.css
src/assets/scss/spartan/custom/_sidebar-and-main-panel.scss
src/components/Share/SharePool.js
src/components/Wallet/Wallet.js
src/views/pages/Pools/Liquidity.js
src/views/pages/Pools/Liquidity2.js

I include the wallet dropdown where shows the available coins, in case that there is a thought that it is not helpful then feel free to revert it

Wallet dropdown 132

---

src/components/Footer/Footer.js
src/components/RecentTxns/RecentTxns.js

recentTxns global closes #226

---

src/components/DataManager/DataManager.js
src/routes.js
src/store/bondVault/actions.js
src/views/pages/Bond/Bond.js
src/views/pages/Bond/BondTable.js
src/views/pages/Dao/LockEarn.js
src/views/pages/Dao/Overview.js
src/views/pages/Pools/AddLiquidity.js
src/views/pages/Swap/Swap.js

mobile responsive updates

---

src/utils/web3Utils.js
src/views/pages/Swap/SwapPair.js

improve APY logic

---

src/components/WalletSelect/WalletSelect.js

Added stakedSynths to walletSelect
Cleaned up some terminology
Fixed the assetAddresses for copy/metamask
closes #257

update walletSelect for synthStaking

---

src/views/pages/Swap/Swap.js

Swap page improvements

---

src/components/layout/Common.js
src/locales/en/translation.json
src/locales/es/translation.json
src/routes.js

I wanted to add in the google sheet but I don't have permission for editing

translate sidebar to Spanish

---

src/assets/scss/spartan/custom/_nav.scss
src/assets/scss/spartan/custom/utilities/_helper.scss
src/components/Approval/Approval.js
src/views/pages/Pools/AddLiquidity.js
src/views/pages/Pools/BondLiquidity.js
src/views/pages/Pools/Overview.js
src/views/pages/Swap/Swap.js

Fixes #286, #305
- Refactored Approval component
- Hiding 'Join pool', 'Swap' and 'Bond' buttons if approval required
- Apply correct mouse cursor to tabs globally

Add Liquidity fix & more

---

.firebaserc
.github/workflows/main.yml
firebase.json

init deploy

---

src/Providers.js
src/components/AssetSelect/AssetSelect.js
src/components/Common/LanguageDropdown.js
src/components/Common/WrongNetwork.js
src/components/WalletSelect/WalletSelect.js
src/components/layout/Common.js
src/utils/web3Utils.js
src/views/pages/Bond/Bond.js
src/views/pages/Bond/BondItem.js
src/views/pages/Pools/PoolItem.js
src/views/pages/Swap/SwapPair.js
src/views/pages/Upgrade/Upgrade.js
src/views/pages/Vault/DaoVault.js
src/views/pages/Vault/SynthVault.js
src/views/pages/Vault/SynthVaultItem.js

closes #334 
see commits & relevant issues for comments

Upgrade #334

---

src/assets/scss/spartan/custom/_variables.scss

update font imports

---

src/Providers.js
src/components/WalletSelect/WalletSelect.js
src/components/WalletSelect/walletTypes.js
src/views/pages/Upgrade/Upgrade.js

walletConnect fix for upgrade page
closes #355
*MIGHT* re-open #350
test on live after merge

walletConnect fix

---

.gitignore
.idea/SpartanProtocol-DAppV2_FIX.iml
.idea/codeStyles/Project.xml
src/Providers.js
src/assets/css/styles.css
src/components/Footer/Footer.js
src/components/layout/Common.js

1st commit✌️These are just some small cleanups. I was annoyed by the broken scroll on the pages.
I've seen an addition of the latest transaction in the footer. This changed the size of the footer with a side effect on the content class.
Also removed some things I thought could be removed or improved. I've manually checked regression I see we have no tests, not a problem, maybe something for the future

Small fixes

---

src/assets/css/styles.css
src/components/Footer/Footer.js

Uncontrolled Tooltips inserted

---

src/components/Common/LanguageDropdown.js

fix wrong fallback flag

---

src/App.js
src/Providers.js
src/assets/css/styles.css
src/assets/scss/spartan/custom/_sidebar-and-main-panel.scss
src/assets/scss/spartan/custom/_type.scss
src/components/DataManager/DataManager.js
src/components/Drawer/Backdrop.js
src/components/Drawer/Drawer.js
src/components/Drawer/styles.scss
src/components/Footer/Footer.js
src/components/Footer/Footer.scss
src/components/RecentTxns/RecentTxns.js
src/components/layout/Common.js

So obviously, I took my time, it was finished quite some time ago, however some things came up :(
Anyhow I took a look in how the transactions are build up. It's only based on the current session, is that right?
On a refresh my transactions are gone. It it meant to only show own transactions or all transactions. 
I would like to improve on the component but Im not sure what its supposed to do so I'll keep it like this for now.

Create a drawer for latest transactions

---

src/components/WalletSelect/WalletSelect.js

updated ranks

---

package.json
src/components/Share/ShareLink.js

switch to native clipboard function and remove react-copy-to-clipboard plugin #464

switch to native clipboard function #464

---

src/components/Common/AddressConn.js

Reload window on metamask account change

---

src/components/WalletSelect/Synths.js

thanks @jacobostel !
some changes; see c051d44
ref: issue #184 & #503

#184 synthusd

---

src/assets/scss/spartan/custom/_badge.scss
src/components/Approval/Approval.js
src/components/DataManager/DataManager.js
src/components/RecentTxns/RecentTxns.js
src/components/WalletSelect/LPs.js
src/store/bond/actions.js
src/store/dao/actions.js
src/store/pool/actions.js
src/store/router/actions.js
src/store/sparta/actions.js
src/store/synth/actions.js
src/store/utils/actions.js
src/store/web3/actions.js
src/utils/math/utils.js
src/utils/web3.js
src/views/pages/Bond/BondItem.js
src/views/pages/Pools/LiqAdd.js
src/views/pages/Pools/LiqBond.js
src/views/pages/Pools/LiqRemove.js
src/views/pages/Swap/Swap.js
src/views/pages/Swap/SwapPair.js
src/views/pages/Synths/Overview.js

- parsetxn logic completed; ready for next phase
- will need to come back and plug in changes after next deploy (event changes)
- also plugged in some loading states for confirm txn buttons & clear inputs on confirm

#502 parse txns for recent txns

---

src/views/pages/Swap/Swap.js

#521 swap fresh load issue

---

src/components/Approval/Approval.js
src/components/WalletSelect/WalletSelect.js
src/locales/en/translation.json
src/utils/math/router.js
src/views/pages/Dao/NewProposal.js
src/views/pages/Dao/ProposalItem.js
src/views/pages/Upgrade/Upgrade.js
src/views/pages/Vault/Components/DaoDepositModal.js
src/views/pages/Vault/Components/DaoWithdrawModal.js
src/views/pages/Vault/Components/SynthDepositModal.js
src/views/pages/Vault/Components/SynthHarvestAllModal.js
src/views/pages/Vault/Components/SynthHarvestModal.js
src/views/pages/Vault/Components/SynthWithdrawModal.js
src/views/pages/Vault/SynthVault.js
src/views/pages/Vault/SynthVaultItem.js

- finished off adding BNB/gas checks
- added more modals / confrims throughout the vaults (mainly synthvault)
- added harvestAll info-modal (and confirm) to synthVault
- added harvestSingle modal (with confirm) to synthVault
- added withdraw modal to synthVault
- various other changes

ux changes

---

src/components/AssetSelect/AssetSelect.js
src/components/WalletSelect/Assets.js
src/components/WalletSelect/LPs.js
src/components/WalletSelect/Synths.js
src/locales/en/translation.json
src/store/web3/actions.js

- add total value to tokens, LPs and Synths on the WalletSelect
- fixed Add to metamask, #543

totalValue+issue543

---

src/utils/web3.js

disable TW api (CORS issue) until fixed

disable TW api

---

src/utils/math/router.js

- fix incorrect synthcap for doubleswap+mint events

fix incorrect synthCap

---

src/components/WalletSelect/WalletSelect.js
src/utils/web3React.js
yarn.lock

- Auto-detect when user has completed the confirmation to connect to WalletConnect via mobile app
- Changed the wallet auto-try connect (first time on dapp load) to be dependent on web3.rpcs so it actually runs every time the rpcs are updated but only actions `checkWallet()` if there is no wallet.account connected

Improve WalletConnect behaviour

---

src/locales/en/translation.json
src/utils/extCalls.js
src/views/pages/Positions/Overview.js

positions use blocks for time

---

src/views/pages/Vaults/SynthVaultItem.js

will need to make a custom function to make this instantly compounding as it doesn't have the nuances that liquidity does in regards to apy

fix synth apy

---

src/views/pages/Vaults/Components/SynthHarvestAllModal.js

Fix synth harvest all

---

src/views/pages/Liquidity/Components/Metrics.js
src/views/pages/Swap/Components/Metrics.js

check for stale metrics

---

src/components/Share/ShareLink.js
src/views/pages/Liquidity/LiqAdd.js
src/views/pages/Liquidity/LiqRemove.js
src/views/pages/Swap/Swap.js
src/views/pages/Synths/Overview.js

closes #721
- add shortened token address under every selected asset throughout dapp
- add 'copy' button next to each
- add 'view bscscan' button next to each

add token addresses below selected asset

---

src/components/Share/index.js
src/containers/Dao/components/AssetSelect.js
src/utils/web3.js

- add new rpcs
- improve share url behaviour
- add sanity checks new dao proposal to add curated

Samus 03 mar22

---

src/assets/styles/global.scss
src/containers/Common/Sidebar/index.js
src/containers/Common/Sidebar/styles.module.scss
src/containers/Common/SidebarLg/index.js
src/containers/Common/SidebarLg/styles.module.scss
src/utils/math/nonContract.js

bunch of sideNav changes for desktop and mobile, merge and test on various devices/browsers

sideNav changes check mobile

---

src/assets/styles/global.scss

I made changes to the sort icons in both light and dark mode when being manipulated.

fix sort icon colors

---

src/components/AssetSelect/index.js
src/containers/Liquidity/LiqAdd.js

fixed addAsym edge case bug (selection changing to different pool in some instances)
fixed Add 'trigger' increment on 'clear' to assetselect search filter - closes #816

small changes

---

src/components/WalletSelect/index.js

TrustWallet changes #857

---

src/components/WalletSelect/index.js
src/store/web3/index.js

- add TrustWallet to the pre-existing network-change logic (MetaMask method)
closes #863

add network change to TW

---

src/utils/web3.js

- added nodereal meganode rpc for public testing

add-node-real-testing

---

src/containers/Pools/index.js
src/providers/Theme/index.js

OnLoad checks users' system-theme settings. If it isn't dark mode, it will set the Dapp to dark mode, thus making it the default setting. Added some code for future in case we go towards the preferred theme approach by user's system setting and new theme colors. Checking it if the user changes it mid-use and changes the Dapp accordingly.

Change default theme#888

---

src/containers/FiatOnboard/index.js

- when viewing onboarding module on mobile device it will now only show the iframe without the information about the onboarding etc
closes #886

only show onboard iframe on mobile

---

src/components/WalletSelect/index.js
src/components/WalletSelect/walletTypes.js
src/utils/web3config.js

- fixed the binance wallet integration
- not heavily tested for edge cases, just for expected functionality
closes #916

binance wallet integration

---

public/index.html

- reimplemented the CSP rules (will need to be tested in wallet browsers etc, this is where things broke last time)

re-implement CSP

---

src/components/AssetSelect/index.js
src/components/Icons/index.js
src/components/WalletSelect/index.js
src/containers/Dao/components/AssetSelect.js
src/containers/Liquidity/Components/Charts/ChartRevenue.js
src/containers/Liquidity/Components/Charts/ChartSwapDemand.js
src/containers/Liquidity/Components/Charts/ChartTVL.js
src/containers/Liquidity/Components/Charts/ChartTxnCount.js
src/containers/Liquidity/Components/Charts/ChartVolume.js
src/containers/Liquidity/Components/TxnModal.js
src/containers/Swap/Components/Charts/ChartPrice.js
src/containers/Synths/components/AssetSelect.js
src/containers/Vaults/BondVaultItem.js
src/containers/Vaults/Components/DaoDepositModal.js
src/containers/Vaults/Components/DaoWithdrawModal.js
src/containers/Vaults/Components/SynthWithdrawModal.js

Went through most components and updated comments to correctly list out the possible params

update props comments

---

package.json

- bumped node to 18.x on the host

trigger redeploy

---

public/index.html
src/containers/Common/DataManager/index.js
src/containers/Friends/index.js
src/containers/Friends/types.js
src/containers/Synths/index.js
src/store/dao/index.js
src/store/synth/index.js
src/store/web3/index.js

Cleanup after big wagmi viem merge

---

src/containers/Pools/NewPool.js
src/store/pool/index.js

- rewrote most of the `create pool` DOM & state logic to improve UX whilst investigating a user issue deploying a new pool
- couldnt find the edge case reported but will return to this and try again later

Rewrite create pool
